#!/usr/bin/env python

# This program is meant to run as a background process when starting up the raspberry pi.
# This script will routinely check the CPU temperature and will shut the raspberry pi down if the temperature
# is getting to high.

import os
import time
import datetime
import subprocess
import random



def mt():
        while True:
                time.sleep(60)
                temp = os.popen("vcgencmd measure_temp").readline()
                t = temp.strip()[5:-2]
                t = float(t)
########################
                if t >= 55:				#if temp is above or equal to 55 degrees Celcius.
			num = random.randint(1,30)
			num2 = random.randint(1,30)
			num3 = (num + num2)*0.5
			print "REBOOTING IN [ {} ] SECONDS!!! CPU TEMP ABOVE 55' C".format(num3)
			time.sleep(num3)
                        f1 = open('tempCrash','a')
                        cTime = str(datetime.datetime.now())
                        cTime = cTime.strip()[:10]
                        msg = '\n' + cTime + "\nShutting down because cpu temp is above 55'C\n"
                        f1.write(msg)
                        f1.close()
                        subprocess.call(['sudo halt'], shell = True)	# shuts the raspberry pi down.



#####################################################################

mt()


